### ISSUE TITLE
安装不了

### ISSUE THREAD

**Issue by Gumoumou** [atticus-lv/super_io#1]
首先是zip文件有问题，直接安装没有反应，windows提示zip文件夹无效。于是我解压后重新打包了一份zip来安装可以安装了但是报错。

Traceback (most recent call last):
  File "D:\APP\blender2.93.4\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\guxiuyi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\super_io-master\__init__.py", line 45, in <module>
    globals()[name] = importlib.import_module(name)
  File "D:\APP\blender2.93.4\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\guxiuyi\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\super_io-master\ops\ops_super_import.py", line 20, in <module>
    from ..ui.icon_utils import RSN_Preview
ModuleNotFoundError: No module named 'super_io-master.ui'

**Comment by atticus-lv** [comment]
可以直接按绿色下载按钮, release那个有问题，我更新下
现在ok了
