### ISSUE TITLE
Super Import in Houdini 19 does not work

### ISSUE THREAD

**Issue by gerroon** [atticus-lv/super_io#29]
Hi

Thanks for the addon. I was able to install it on Blender 3.3 Windows and Houdini 19 Windows. 

I can send objects from Houdini to Blender, but I am getting this error inn Houdini when I try to import what I have exported from Blender. I tried .obj, .fbx and .abc but none of these formats made it work.

```
Traceback (most recent call last):
  File "spio_import", line 143, in <module>
  File "spio_import", line 61, in main
AttributeError: 'NoneType' object has no attribute 'pwd'

```

Add an object in Blender
Select it and use super export
In Houdini , click on Super import

**Comment by atticus-lv** [comment]
Thanks for reporting the issue. 
Make Sure you have assign the shortcut for this two shelf tool, else it won't work
Call them with shortcut when your mouse is on the network editor (sop level)

**Comment by atticus-lv** [comment]
I will add the readme file later in the houdini package part
