### ISSUE TITLE
Blender 3.1.2 插件出现错误（Error in Blender 3.1.2）

### ISSUE THREAD

**Issue by Dyrus95** [atticus-lv/super_io#31]
Traceback (most recent call last):
  File "D:\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\blender\3.1\scripts\addons\super_io-master\__init__.py", line 24, in <module>
    from . import translation, ui, ops, addon, preferences
  File "D:\blender\3.1\scripts\addons\super_io-master\addon\__init__.py", line 1, in <module>
    from . import addon_updater, asset_helper, importer
  File "D:\blender\3.1\scripts\addons\super_io-master\addon\importer\__init__.py", line 2, in <module>
    from . import op_import_ies, op_import_zip, ops_addon_import, op_blend_import_and_assign, op_import_pbr_from_url
ImportError: cannot import name 'op_import_pbr_from_url' from partially initialized module 'super_io-master.addon.importer' (most likely due to a circular import) (D:\blender\3.1\scripts\addons\super_io-master\addon\importer\__init__.py)

**Comment by atticus-lv** [comment]
下载旁边的release而不是直接点code的下载zip
